# Generated by Django 5.2.8 on 2025-11-29 16:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=100)),
                ('template_text', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='LegalSpecialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'legal_specializations',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('setting_value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('LAWYER', 'Lawyer'), ('ADMIN', 'Admin'), ('NGO_SUPPORT', 'NGO Support')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('language_preference', models.CharField(choices=[('BN', 'Bangla'), ('EN', 'English')], default='BN', max_length=2)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('admin_level', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MODERATOR', 'Moderator'), ('SUPPORT', 'Support')], default='MODERATOR', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('context_window_usage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('citations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aiconversation')),
            ],
            options={
                'db_table': 'ai_messages',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_rating', models.CharField(choices=[('THUMBS_UP', 'Thumbs Up'), ('THUMBS_DOWN', 'Thumbs Down')], max_length=20)),
                ('correction_text', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('INACCURATE', 'Inaccurate'), ('UNSAFE', 'Unsafe'), ('HELPFUL', 'Helpful'), ('OTHER', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aimessage')),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('DOC_REQUESTED', 'Doc Requested'), ('SCHEDULED', 'Scheduled'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='CaseActivityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
            ],
            options={
                'db_table': 'case_activity_log',
            },
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_en', models.CharField(max_length=100)),
                ('full_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=50, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('geo_division', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_district', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'citizen_profiles',
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=512)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('encryption_hash', models.CharField(max_length=64)),
                ('encryption_key_id', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentShareToken',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evidencedocument')),
            ],
            options={
                'db_table': 'document_share_tokens',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.evidencedocument')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='AIDocumentChunk',
            fields=[
                ('chunk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content_text', models.TextField()),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evidencedocument')),
            ],
            options={
                'db_table': 'ai_document_chunks',
            },
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bar_council_number', models.CharField(max_length=50, unique=True)),
                ('license_issue_date', models.DateField()),
                ('full_name_en', models.CharField(max_length=100)),
                ('full_name_bn', models.CharField(max_length=100)),
                ('bio_en', models.TextField(blank=True, null=True)),
                ('bio_bn', models.TextField(blank=True, null=True)),
                ('chamber_address', models.TextField(blank=True, null=True)),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('consultation_fee_online', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consultation_fee_offline', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lawyer_profiles',
            },
        ),
        migrations.CreateModel(
            name='LawyerAvailabilitySlot',
            fields=[
                ('slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_type', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person'), ('BOTH', 'Both')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyerprofile')),
            ],
            options={
                'db_table': 'lawyer_availability_slots',
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyerprofile')),
            ],
            options={
                'db_table': 'consultation_bookings',
            },
        ),
        migrations.CreateModel(
            name='CasePrivateNote',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='PRIVATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyerprofile')),
            ],
            options={
                'db_table': 'case_private_notes',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='api.lawyerprofile'),
        ),
        migrations.CreateModel(
            name='LawyerReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultationbooking')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyerprofile')),
            ],
            options={
                'db_table': 'lawyer_reviews',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.legalspecialization'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CASE_UPDATE', 'Case Update'), ('BOOKING', 'Booking'), ('SYSTEM', 'System'), ('REMINDER', 'Reminder'), ('MESSAGE', 'Message')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='LawyerSpecializationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyerprofile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.legalspecialization')),
            ],
            options={
                'db_table': 'lawyer_specializations_map',
                'unique_together': {('lawyer', 'specialization')},
            },
        ),
    ]
