# Generated by Django 5.2.8 on 2025-12-01 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_default_auth_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.case'),
        ),
    ]
