# Generated by Django 5.2.8 on 2025-12-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationbooking',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.case'),
        ),
    ]
